Makefile
README.md
ci/azure-pipelines.yml

fix: azure badge

---

docs/overview/bloc-did-method.md

feat: Revised did:bloc spec

---

test/bdd/fixtures/universalresolver/docker-compose.yml
test/bdd/fixtures/well-known-server/config/testnet.trustbloc.dev.json
test/bdd/fixtures/well-known-server/docker-compose.yml

chore: Add static server to host well known

---

README.md
docs/build.md

docs: Create build doc for build instructions

---

.golangci.yml
Makefile
README.md
ci/azure-pipelines.yml
cmd/did-method-rest/go.mod
cmd/did-method-rest/main.go
cmd/did-method-rest/startcmd/start.go
docs/build.md
go.mod
images/did-method-rest/Dockerfile
pkg/did/client.go
pkg/did/client_test.go
pkg/internal/mock/discovery/mock_service.go
pkg/internal/mock/selection/mock_service.go
pkg/restapi/didmethod/controller.go
pkg/restapi/didmethod/operation/operations.go
pkg/vdri/trustbloc/discovery/staticdiscovery/service.go
pkg/vdri/trustbloc/discovery/staticdiscovery/service_test.go
pkg/vdri/trustbloc/selection/staticselection/service.go
pkg/vdri/trustbloc/selection/staticselection/service_test.go
pkg/vdri/trustbloc/vdri.go
pkg/vdri/trustbloc/vdri_test.go
scripts/check_unit.sh
scripts/generate_test_keys.sh
test/bdd/bddtests_test.go
test/bdd/fixtures/did-method-rest/docker-compose.yml
test/bdd/go.mod
test/bdd/pkg/vdri/vdri_steps.go

chore: rename repo to trustbloc-did-method

---

pkg/vdri/trustbloc/vdri.go
pkg/vdri/trustbloc/vdri_test.go

fix: rename bloc to trustbloc

---

test/bdd/fixtures/universalresolver/docker-compose.yml
test/bdd/fixtures/universalresolver/run-uni-resolver-web.sh

related https://github.com/decentralized-identity/universal-resolver/issues/93

fix: uni-resolver image

---

test/bdd/fixtures/universalresolver/docker-compose.yml

chore: update uni-resolver-web image tag to 0.1.0

---

docs/overview/trustbloc-did-method.md

Resolving todos, integrating feedback, rewriting clunky sections, and finalizing the spec.

docs: Updating Spec

---

cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/did/client.go
test/bdd/fixtures/sidetree-mock/.env
test/bdd/go.sum

chore: Update sidetree-mock image tag

---

pkg/vdri/trustbloc/discovery/staticdiscovery/service.go
pkg/vdri/trustbloc/discovery/staticdiscovery/service_test.go
scripts/generate_test_keys.sh
test/bdd/features/did_method_e2e.feature
test/bdd/fixtures/discovery-server/docker-compose.yml
test/bdd/fixtures/stakeholder-server/docker-compose.yml

chore: change default perfix to https

---

pkg/did/client.go
pkg/vdri/trustbloc/discovery/staticdiscovery/service.go
pkg/vdri/trustbloc/vdri.go
pkg/vdri/trustbloc/vdri_test.go
test/bdd/fixtures/sidetree-mock/.env
test/bdd/fixtures/stakeholder-server/config-data/stakeholder.one:8088.json

chore: Enable tls for sidetree-mock

---

cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/vdri/trustbloc/vdri.go
pkg/vdri/trustbloc/vdri_test.go

feat: Compare docs from all endpoints

---

docs/overview/consortium.schema.json
docs/overview/member.schema.json
docs/overview/trustbloc-did-method.md

- Sidetree parameters
- DID syntax ABNF
- well-known DID configuration
- Some section reordering and edits

docs: Revised spec based on suggestions

---

cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/did/client.go
test/bdd/fixtures/sidetree-mock/.env
test/bdd/go.sum

chore: Update sidetree-mock revision to 57120a4

---

cmd/did-method-rest/go.sum
go.mod
go.sum
test/bdd/fixtures/sidetree-mock/.env
test/bdd/go.sum

chore: update sidetree-mock image

---

pkg/vdri/trustbloc/config/consortium.go
pkg/vdri/trustbloc/config/consortium_test.go
pkg/vdri/trustbloc/config/stakeholder.go
pkg/vdri/trustbloc/config/stakeholder_test.go
pkg/vdri/trustbloc/discovery/staticdiscovery/service.go
pkg/vdri/trustbloc/discovery/staticdiscovery/service_test.go
test/bdd/fixtures/discovery-server/config-data/consortium.json
test/bdd/fixtures/stakeholder-server/config-data/stakeholder.one:8088.json

chore: Updated config schema to match spec

---

pkg/did/client.go
pkg/did/client_test.go
pkg/restapi/didmethod/operation/models.go
pkg/restapi/didmethod/operation/operations.go
pkg/restapi/didmethod/operation/operations_test.go
test/bdd/fixtures/universalresolver/docker-compose.yml
test/bdd/pkg/vdri/vdri_steps.go

feat: Add option for createDID to add service

---

docs/spec/trustbloc-did-method.md

docs: fix example did-trustbloc paths

---

docs/spec/trustbloc-did-method.md

docs: minor fix to capitalization.

---

docs/spec/trustbloc-did-method.md

docs: add did:key prefix to examples

---

docs/spec/consortium.schema.json
docs/spec/trustbloc-did-method.md

docs: update spec to use JWK

---

docs/spec/consortium.schema.json
docs/spec/member.schema.json
docs/spec/trustbloc-did-method.md
pkg/vdri/trustbloc/config/consortium.go
pkg/vdri/trustbloc/config/consortium_test.go
pkg/vdri/trustbloc/config/stakeholder_test.go
test/bdd/fixtures/discovery-server/config-data/consortium.json
test/bdd/fixtures/stakeholder-server/config-data/stakeholder.one:8088.json

docs: replace dash with underscore in spec

---

pkg/restapi/didmethod/operation/models.go
pkg/restapi/didmethod/operation/operations.go
pkg/restapi/didmethod/operation/operations_test.go
test/bdd/pkg/vdri/vdri_steps.go

fix: AddServices struct for register DID request

---

docs/spec/consortium.schema.json
docs/spec/trustbloc-did-method.md

- initial privacy considerations.
- some minor fixes from previous PR.

docs: initial privacy considerations section

---

cmd/did-method-rest/startcmd/start.go

fix: tls-systemcertpool flag

---

pkg/vdri/trustbloc/vdri.go
pkg/vdri/trustbloc/vdri_test.go

fix: comment out logic to compare response from each endpoint

---

cmd/did-method-rest/startcmd/start.go
cmd/did-method-rest/startcmd/start_test.go

feat: Remove hard-coded memory storage

---

cmd/did-method-rest/go.mod
cmd/did-method-rest/go.sum
go.mod
go.sum
test/bdd/go.mod
test/bdd/go.sum

chore: Update aries revision

---

Makefile
pkg/did/client.go
pkg/did/client_test.go
pkg/did/doc.go
pkg/restapi/didmethod/operation/models.go
pkg/restapi/didmethod/operation/operations.go
test/bdd/fixtures/discovery-server/docker-compose.yml
test/bdd/pkg/vdri/vdri_steps.go

feat: Add public key struct

---

go.mod
pkg/restapi/didmethod/operation/operations.go
pkg/restapi/didmethod/operation/operations_test.go

fix: add '#' to PublicKeyDIDURL

---

pkg/did/client_test.go
pkg/did/doc.go
pkg/restapi/didmethod/operation/models.go
pkg/restapi/didmethod/operation/operations.go
test/bdd/features/did_method_e2e.feature
test/bdd/pkg/vdri/vdri_steps.go

closes #92 
Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

feat: Support for EC key

---

cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/did/client.go
pkg/did/client_test.go
pkg/did/doc.go
test/bdd/features/did_method_e2e.feature
test/bdd/fixtures/sidetree-mock/.env
test/bdd/go.sum
test/bdd/pkg/vdri/vdri_steps.go

chore: Update sidetree-core revision

---

go.sum
pkg/did/client_test.go
pkg/did/doc.go
test/bdd/features/did_method_e2e.feature
test/bdd/pkg/vdri/vdri_steps.go

chore: add P256KeyType

---

ci/azure-pipelines.yml
cmd/did-method-rest/go.sum
go.mod
go.sum
test/bdd/fixtures/sidetree-mock/.env
test/bdd/go.sum
test/bdd/pkg/vdri/vdri_steps.go

chore:  Update sidetree-core revision

---

cmd/did-method-rest/go.mod
cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/restapi/didmethod/operation/models.go
pkg/restapi/didmethod/operation/operations.go
pkg/restapi/didmethod/operation/operations_test.go
test/bdd/features/did_method_e2e.feature
test/bdd/go.mod
test/bdd/go.sum
test/bdd/pkg/vdri/vdri_steps.go

chore: add DIDDocument to RegisterDIDRequest 

---

cmd/did-method-rest/go.sum
go.mod
go.sum
test/bdd/go.sum

chore: revert aries-framework-go revision

---

go.sum
pkg/restapi/didmethod/operation/models.go
pkg/restapi/didmethod/operation/operations.go
pkg/restapi/didmethod/operation/operations_test.go

fix: api for create did

---

cmd/did-method-rest/go.mod
cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/did/client_test.go
pkg/did/doc.go
test/bdd/go.mod
test/bdd/go.sum
test/bdd/pkg/vdri/vdri_steps.go

fix: use elliptic.Marshal

---

cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/did/doc.go
test/bdd/fixtures/sidetree-mock/.env
test/bdd/go.sum

chore: update sidetree-core-go revision

---

pkg/did/doc.go

Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

chore: Add Sidetree Usage constants

---

cmd/did-method-rest/go.mod
cmd/did-method-rest/go.sum
go.mod
go.sum
test/bdd/fixtures/sidetree-mock/.env
test/bdd/go.mod
test/bdd/go.sum

chore: update sidetree-mock and aries revision

---

pkg/restapi/didmethod/operation/models.go

feat: add Purpose field to uniregistrar response

---

.golangci.yml
cmd/did-method-rest/go.sum
go.sum
pkg/internal/common/canonicalizer/canonicalizer.go
pkg/internal/common/jsoncanonicalizer/README.md
pkg/internal/common/jsoncanonicalizer/es6numfmt.go
pkg/internal/common/jsoncanonicalizer/jsoncanonicalizer.go
pkg/vdri/trustbloc/vdri.go

fix: Compare canonicalized json representations of did docs when verifying integrity

---

pkg/vdri/trustbloc/vdri.go

fix: temporary disable mismatch check

---

pkg/vdri/trustbloc/vdri_test.go

fix: remove mismatch test

---

pkg/vdri/trustbloc/vdri.go

chore: use debug log

---

ci/azure-pipelines.yml

chore: push image driver-did-trustbloc

---

README.md
ci/version_var.sh
cmd/did-method-rest/go.mod
cmd/did-method-rest/go.sum
go.mod
go.sum
test/bdd/fixtures/sidetree-mock/.env
test/bdd/go.mod
test/bdd/go.sum

Dependency tags and usage documentation.

chore: update for 0.1.3 release

---

ci/version_var.sh

chore: Complete release v0.1.3

---

ci/azure-pipelines.yml

ci: remove publishing of old image name

---

ci/azure-pipelines.yml
ci/version_var.sh

ci: publish snapshot images to snapshot repo

---

test/bdd/features/did_method_e2e.feature
test/bdd/fixtures/sidetree-mock/.env
test/bdd/pkg/vdri/vdri_steps.go

fix: create two test to resolve DID (universalresolver, sidetree-mock)

---

cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/vdri/trustbloc/config/memorycacheconfig/service.go
pkg/vdri/trustbloc/config/memorycacheconfig/service_test.go
pkg/vdri/trustbloc/models/consortium.go
pkg/vdri/trustbloc/models/consortium_test.go
pkg/vdri/trustbloc/models/stakeholder.go
pkg/vdri/trustbloc/models/stakeholder_test.go
pkg/vdri/trustbloc/vdri.go
test/bdd/go.sum

Caches requested configs up to their cache lifetime to avoid repeated fetches.
Fixes #140

feat: In-Memory Caching Config Service

---

cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/vdri/trustbloc/config/signatureconfig/service.go
pkg/vdri/trustbloc/config/signatureconfig/service_test.go
pkg/vdri/trustbloc/vdri.go
test/bdd/go.sum

feat: consortium config signature verification

---

cmd/did-method-cli/createconfigcmd/createconfig.go
cmd/did-method-cli/go.sum
cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/did/client.go
pkg/did/client_test.go
pkg/did/doc.go
pkg/restapi/didmethod/operation/models.go
pkg/restapi/didmethod/operation/operations.go
test/bdd/fixtures/sidetree-mock/.env
test/bdd/go.sum
test/bdd/pkg/vdri/vdri_steps.go

Update sidetree-core:
- send recovery and update commitment values in create request
Closes #152

chore: update sidetree-core

---

pkg/vdri/trustbloc/vdri.go

chore: disabled signature verification temporarily

---

cmd/did-method-cli/createconfigcmd/createconfig.go
cmd/did-method-cli/createconfigcmd/createconfig_test.go
pkg/did/client.go
pkg/did/client_test.go
pkg/did/doc.go
pkg/did/doc_test.go
pkg/vdri/trustbloc/config/httpconfig/service_test.go
pkg/vdri/trustbloc/config/signatureconfig/service.go
pkg/vdri/trustbloc/config/verifyingconfig/service.go
pkg/vdri/trustbloc/didconfiguration/helpers.go
pkg/vdri/trustbloc/didconfiguration/helpers_test.go
pkg/vdri/trustbloc/discovery/staticdiscovery/service_test.go
pkg/vdri/trustbloc/models/didconfiguration.go
test/bdd/bddtests_test.go
test/bdd/fixtures/discovery-server/docker-compose.yml
test/bdd/fixtures/stakeholder-server/docker-compose.yml
test/bdd/fixtures/universalresolver/run-uni-resolver-web.sh
test/bdd/generate_config.sh
test/bdd/go.sum
test/bdd/pkg/context/context.go

feat: create did-configuration

---

pkg/internal/mock/didconfiguration/mock_service.go
pkg/vdri/trustbloc/config/httpconfig/service.go
pkg/vdri/trustbloc/didconfiguration/helpers.go
pkg/vdri/trustbloc/didconfiguration/helpers_test.go
pkg/vdri/trustbloc/didconfiguration/service.go
pkg/vdri/trustbloc/didconfiguration/service_test.go
pkg/vdri/trustbloc/vdri.go
pkg/vdri/trustbloc/vdri_test.go

feat: did configuration creation and verification

---

cmd/did-method-rest/startcmd/start.go
pkg/restapi/healthcheck/controller.go
pkg/restapi/healthcheck/controller_test.go
pkg/restapi/healthcheck/operation/operations.go
pkg/restapi/healthcheck/operation/operations_test.go
test/bdd/bddtests_test.go
test/bdd/features/healthcheck_api.feature
test/bdd/go.mod
test/bdd/go.sum
test/bdd/pkg/common/common_steps.go

feat: add heatlhcheck api

---

test/bdd/fixtures/sidetree-mock/.env

chore: update sidetree-mock image to 0.1.4

---

pkg/vdri/trustbloc/vdri.go

feat: signature validation now behind an option

---

ci/version_var.sh
cmd/did-method-cli/go.mod
cmd/did-method-cli/go.sum
cmd/did-method-rest/go.sum
go.mod
go.sum
test/bdd/go.mod
test/bdd/go.sum

chore: Release 0.1.4

---

ci/version_var.sh

chore: Complete Release 0.1.4

---

cmd/did-method-cli/go.sum
cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/did/client.go
test/bdd/fixtures/sidetree-mock/.env
test/bdd/go.sum

Update to latest sidetree-core, sidetree-mock
Closes #173

chore: Update to latest sidetree-core, sidetree-mock

---

cmd/did-method-rest/startcmd/start.go
cmd/did-method-rest/startcmd/start_test.go
pkg/restapi/didmethod/operation/operations.go
pkg/vdri/trustbloc/vdri.go
pkg/vdri/trustbloc/vdri_test.go
test/bdd/fixtures/did-method-rest/docker-compose.yml
test/bdd/generate_config.sh

feat: parameter/env to enable signature validation in did-method-rest

---

Makefile
cmd/did-method-cli/confighashcmd/confighash.go
cmd/did-method-cli/confighashcmd/confighash_test.go
cmd/did-method-cli/createconfigcmd/createconfig_test.go
cmd/did-method-cli/go.mod
cmd/did-method-cli/go.sum
cmd/did-method-cli/main.go
cmd/did-method-cli/sample/config.json
cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/restapi/didmethod/operation/operations.go
pkg/vdri/trustbloc/vdri.go
pkg/vdri/trustbloc/vdri_test.go
scripts/generate_config_hash.sh
test/bdd/fixtures/sidetree-mock/.env
test/bdd/fixtures/sidetree-mock/docker-compose.yml
test/bdd/fixtures/universalresolver/config.json
test/bdd/fixtures/universalresolver/docker-compose.yml
test/bdd/fixtures/wellknown/config.json
test/bdd/go.sum
test/bdd/pkg/vdri/vdri_steps.go

feat: Canonical DID identifier

---

pkg/vdri/trustbloc/didconfiguration/helpers.go
scripts/generate_test_keys.sh
test/bdd/bddtests_test.go
test/bdd/fixtures/stakeholder-server/docker-compose.yml
test/bdd/fixtures/wellknown/config.json
test/bdd/fixtures/wellknown/stakeholdertwo_jwk.json
test/bdd/generate_config.sh

Fixes signature verification for multiple-stakeholder scenarios.

fix: multi-stakeholder verification fix

---

test/bdd/fixtures/universal-registrar/docker-compose.yml

fix: uni-registrar-web image

---

docs/spec/trustbloc-did-method.md

Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

fix: Sidetree spec url

---

.golangci.yml
cmd/did-method-rest/main_test.go
cmd/did-method-rest/startcmd/start.go
pkg/did/client_test.go
pkg/restapi/didmethod/operation/operations.go
pkg/vdri/trustbloc/config/httpconfig/service_test.go
pkg/vdri/trustbloc/config/memorycacheconfig/service.go
pkg/vdri/trustbloc/didconfiguration/service_test.go
pkg/vdri/trustbloc/discovery/staticdiscovery/service_test.go
pkg/vdri/trustbloc/endpoint/service_test.go
pkg/vdri/trustbloc/selection/staticselection/service.go
pkg/vdri/trustbloc/vdri.go
pkg/vdri/trustbloc/vdri_test.go
scripts/check_lint.sh
test/bdd/bddtests_test.go
test/bdd/dockerutil/compose.go
test/bdd/pkg/context/context.go
test/bdd/pkg/vdri/vdri_steps.go

chore: update golangci-lint to v1.31

---

cmd/did-method-cli/createdidcmd/createdid.go
cmd/did-method-cli/createdidcmd/createdid_test.go
pkg/did/client.go
pkg/did/client_test.go
test/bdd/features/did_method_cli.feature
test/bdd/pkg/cli/cli_steps.go

feat: Support direct sidetree endpoint for creating DID CLI

---

scripts/generate_test_keys.sh

chore: Create protected PEM private key

---

cmd/did-method-cli/go.sum
pkg/restapi/didmethod/operation/models.go
pkg/restapi/didmethod/operation/operations.go
test/bdd/pkg/vdri/vdri_steps.go

Rename purpose tag to purposes tag for did method model
Closes #197

chore: rename purpose to purposes

---

cmd/did-method-cli/createconfigcmd/createconfig.go
cmd/did-method-cli/createconfigcmd/createconfig_test.go
cmd/did-method-cli/createdidcmd/createdid.go
pkg/did/client.go
pkg/did/client_test.go
pkg/did/doc.go
pkg/restapi/didmethod/operation/operations.go
pkg/restapi/didmethod/operation/operations_test.go
test/bdd/generate_config.sh

refactor: Remove update and recovery key from public key struct

---

pkg/did/client.go
pkg/did/client_test.go
pkg/did/option.go

feat: Add update DID feature

---

pkg/did/client.go
pkg/did/client_test.go
pkg/did/option/recovery/option.go

feat: Add recover DID feature

---

.gitignore
cmd/did-method-cli/common/common.go
cmd/did-method-cli/common/common_test.go
cmd/did-method-cli/main.go
cmd/did-method-cli/recoverdidcmd/recoverdid.go
cmd/did-method-cli/recoverdidcmd/recoverdid_test.go
scripts/generate_test_keys.sh
test/bdd/features/did_method_cli.feature
test/bdd/fixtures/did-keys/recover/key1_jwk.json
test/bdd/fixtures/did-keys/recover/publickeys.json
test/bdd/fixtures/did-services/recover/services.json
test/bdd/pkg/cli/cli_steps.go

feat: Add CLI feature to recover DID

---

pkg/did/client.go
pkg/did/client_test.go
pkg/did/option/deactivate/option.go

feat: Add deactivate DID feature

---

cmd/did-method-cli/deactivatedidcmd/deactivatedid.go
cmd/did-method-cli/deactivatedidcmd/deactivatedid_test.go
cmd/did-method-cli/main.go
test/bdd/features/did_method_cli.feature
test/bdd/pkg/cli/cli_steps.go

feat: Add CLI feature to deactivate DID

---

cmd/did-method-cli/confighashcmd/confighash_test.go
cmd/did-method-cli/createconfigcmd/createconfig_test.go
cmd/did-method-cli/recoverdidcmd/recoverdid_test.go
cmd/did-method-cli/sample/config.json
cmd/did-method-cli/updatedidcmd/updatedid_test.go
docs/spec/consortium.schema.json
docs/spec/trustbloc-did-method.md
pkg/did/client.go
pkg/did/client_test.go
pkg/internal/mock/config/mock_service.go
pkg/vdri/trustbloc/config/httpconfig/service.go
pkg/vdri/trustbloc/config/httpconfig/service_test.go
pkg/vdri/trustbloc/config/memorycacheconfig/service.go
pkg/vdri/trustbloc/config/memorycacheconfig/service_test.go
pkg/vdri/trustbloc/config/signatureconfig/service.go
pkg/vdri/trustbloc/config/signatureconfig/service_test.go
pkg/vdri/trustbloc/config/verifyingconfig/service.go
pkg/vdri/trustbloc/models/sidetreeconfiguration.go
test/bdd/fixtures/wellknown/config.json

feat: Retrieve sidetree configuration parameters from version endpoint

---

cmd/did-method-cli/confighashcmd/confighash_test.go
cmd/did-method-cli/createconfigcmd/createconfig_test.go
cmd/did-method-cli/sample/config.json
docs/spec/consortium.schema.json
docs/spec/member.schema.json
docs/spec/trustbloc-did-method.md
pkg/vdri/trustbloc/models/consortium.go
pkg/vdri/trustbloc/models/consortium_test.go
pkg/vdri/trustbloc/models/stakeholder_test.go
pkg/vdri/trustbloc/selection/staticselection/service.go
pkg/vdri/trustbloc/vdri.go
test/bdd/fixtures/sidetree-mock/docker-compose.yml
test/bdd/fixtures/wellknown/config.json

refactor: Switch consortium config fields to camel case

---

cmd/did-method-cli/confighashcmd/confighash_test.go
cmd/did-method-cli/createconfigcmd/createconfig.go
cmd/did-method-cli/createconfigcmd/createconfig_test.go
cmd/did-method-cli/sample/config.json
test/bdd/fixtures/wellknown/config.json

fix: rename member_data and consortium_data

---

cmd/did-method-cli/confighashcmd/confighash_test.go
cmd/did-method-cli/createconfigcmd/createconfig_test.go
cmd/did-method-cli/sample/config.json
test/bdd/fixtures/wellknown/config.json

fix: rename genesis_block

---

cmd/did-method-cli/createdidcmd/createdid.go
cmd/did-method-cli/createdidcmd/createdid_test.go
cmd/did-method-cli/updatedidcmd/updatedid.go
cmd/did-method-cli/updatedidcmd/updatedid_test.go

refactor: create and update cli

---

cmd/did-method-cli/createconfigcmd/createconfig.go
cmd/did-method-cli/createconfigcmd/createconfig_test.go
cmd/did-method-cli/internal/configcommon/helpers.go
cmd/did-method-cli/internal/configcommon/helpers_test.go
cmd/did-method-cli/main.go
cmd/did-method-cli/updateconfigcmd/updateconfig.go
cmd/did-method-cli/updateconfigcmd/updateconfig_test.go
pkg/vdri/trustbloc/config/httpconfig/service_test.go
pkg/vdri/trustbloc/config/updatevalidationconfig/service.go
pkg/vdri/trustbloc/config/updatevalidationconfig/service_test.go
pkg/vdri/trustbloc/vdri.go
pkg/vdri/trustbloc/vdri_test.go

feat: cli update config command

---

cmd/did-method-cli/common/common.go
cmd/did-method-cli/common/common_test.go
cmd/did-method-cli/createdidcmd/createdid_test.go
cmd/did-method-cli/recoverdidcmd/recoverdid_test.go
cmd/did-method-cli/sample/key1_jwk.json
cmd/did-method-cli/sample/key2_jwk.json
cmd/did-method-cli/sample/publickeys.json
cmd/did-method-cli/updatedidcmd/updatedid_test.go
docs/cli/create.md
docs/cli/recover.md
docs/cli/update.md
test/bdd/fixtures/did-keys/create/key1_jwk.json
test/bdd/fixtures/did-keys/create/key2_jwk.json
test/bdd/fixtures/did-keys/create/publickeys.json
test/bdd/fixtures/did-keys/recover/key1_jwk.json
test/bdd/fixtures/did-keys/recover/publickeys.json
test/bdd/fixtures/did-keys/update/key2_jwk.json
test/bdd/fixtures/did-keys/update/key3_jwk.json
test/bdd/fixtures/did-keys/update/publickeys.json

fix: add key id to public key json

---

cmd/did-method-cli/createdidcmd/createdid_test.go
cmd/did-method-cli/go.mod
cmd/did-method-cli/go.sum
cmd/did-method-rest/go.sum
go.mod
go.sum
test/bdd/fixtures/sidetree-mock/.env
test/bdd/go.sum
test/bdd/pkg/vdri/vdri_steps.go

Update sidetre-core, sidetree-mock
Clsoes #232

chore: update sidetree-core, sidetree-mock

---

docs/whitepaper/federated_sidetree.md

docs: federated did concept whitepaper

---

docs/whitepaper/federated_sidetree.md

docs: federated whitepaper clarifications

---

docs/whitepaper/federated_sidetree.md

docs: whitepaper updates from feedback

---

ci/version_var.sh
cmd/did-method-cli/go.mod
cmd/did-method-cli/go.sum
cmd/did-method-rest/go.mod
cmd/did-method-rest/go.sum
go.mod
go.sum
test/bdd/fixtures/sidetree-mock/.env
test/bdd/go.mod
test/bdd/go.sum

chore: Release v0.1.5

---

ci/version_var.sh

chore: complete release 0.1.5

---

docs/whitepaper/federated_sidetree.md

docs: whitepaper updates

---

test/bdd/fixtures/sidetree-mock/.env

Update to latest sidetree-mock
Closes #248

chore: update to latest sidetree-mock

---

test/bdd/fixtures/universalresolver/docker-compose.yml

fix: universalresolver/uni-resolver-web image

---

Makefile
ci/azure-pipelines.yml
ci/version_var.sh
images/did-method-rest/Dockerfile
test/bdd/fixtures/did-method-rest/docker-compose.yml
test/bdd/fixtures/sidetree-mock/.env

ci: migrate to ghcr

---

README.md
ci/azure-pipelines.yml
docs/whitepaper/federated_sidetree.md

chore: rename master branch to main

---

test/bdd/bddtests_test.go
test/bdd/fixtures/discovery-server/docker-compose.yml
test/bdd/fixtures/stakeholder-server/docker-compose.yml
test/bdd/generate_config.sh
test/bdd/generate_stub_config.sh
test/bdd/pkg/consortium-config/config_steps.go
test/bdd/pkg/vdri/vdri_steps.go
test/bdd/update_config.sh

chore: docker mount fix

---

cmd/did-method-cli/common/common.go
cmd/did-method-cli/common/common_test.go
cmd/did-method-cli/createconfigcmd/createconfig.go
cmd/did-method-cli/createdidcmd/createdid.go
cmd/did-method-cli/go.mod
cmd/did-method-cli/go.sum
cmd/did-method-cli/recoverdidcmd/recoverdid.go
cmd/did-method-cli/updatedidcmd/updatedid.go
cmd/did-method-rest/go.mod
cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/restapi/didmethod/operation/operations.go
pkg/restapi/didmethod/operation/operations_test.go
test/bdd/go.mod
test/bdd/go.sum
test/bdd/pkg/cli/cli_steps.go

chore: update trustbloc VDR to use purposes

---

cmd/did-method-cli/go.mod
cmd/did-method-cli/go.sum
cmd/did-method-rest/go.sum
go.mod
go.sum
test/bdd/go.mod
test/bdd/go.sum

Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

chore: update with latest AFG including X25519 kw

---

Makefile
ci/azure-pipelines.yml
ci/version_var.sh
images/did-method-cli/Dockerfile

Signed-off-by: ali.alkhalidi <ali.alkhalidi@securekey.com>

chore: addresses #264

---

cmd/did-method-cli/createconfigcmd/createconfig.go
cmd/did-method-cli/createdidcmd/createdid.go
cmd/did-method-cli/deactivatedidcmd/deactivatedid.go
cmd/did-method-cli/go.mod
cmd/did-method-cli/go.sum
cmd/did-method-cli/recoverdidcmd/recoverdid.go
cmd/did-method-cli/updatedidcmd/updatedid.go
cmd/did-method-rest/go.mod
cmd/did-method-rest/go.sum
go.mod
go.sum
pkg/restapi/didmethod/controller.go
pkg/restapi/didmethod/operation/operations.go
pkg/restapi/didmethod/operation/operations_test.go
test/bdd/go.mod
test/bdd/go.sum
test/bdd/pkg/cli/cli_steps.go
test/bdd/pkg/vdri/vdri_steps.go

chore: update trustbloc vdr

---

cmd/did-method-cli/go.mod
cmd/did-method-cli/go.sum
cmd/did-method-rest/go.mod
cmd/did-method-rest/go.sum
go.mod
go.sum
test/bdd/go.mod
test/bdd/go.sum

Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

chore: update latest dependencies

---

ci/version_var.sh

chore: complete Release 0.1.6
